name: Daily ML Job Crawl
on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day
  workflow_dispatch:      # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run Crawler
        run: python crawler.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'ForraCorp-Bot'
          git config --global user.email 'bot@forracorp.com'
          git add jobs.json
          git commit -m "Auto-update: Latest ML Vacancies"
          git push
